BaSP-TG: tasks methods (create and edit)
BaSP-a2022/ayom-b-trackgenix-server pull request #10
Opened 2022-10-10 20:09 UTC by DinoStampella

2022-10-11 18:42 UTC, Licamus commented on src/resources/tasks.js
> +  if (Object.keys(newTask).length !== 2) {
What happens if you enter a wrong key? The task is storages anyway?

2022-10-11 18:53 UTC, DinoStampella commented on src/resources/tasks.js
> +  if (Object.keys(newTask).length !== 2) {
Si Maxi! Creo que no era necesario hacer validaciones para esta problemática

2022-10-12 04:11 UTC, baudraccoverona requested changes

2022-10-12 04:11 UTC, baudraccoverona commented on src/index.js
> +// Dino Stampella Workspace
Please remove this comment

2022-10-12 04:11 UTC, baudraccoverona commented on src/index.js
> +// End workspace (DS)
Remove this one too 😄 🧹

2022-10-12 04:11 UTC, baudraccoverona commented on src/resources/tasks.js
> +      res.send('Task created successfully');
We should improve this error message to be something like this "Task created successfully. ${newTask}"

2022-10-12 04:11 UTC, baudraccoverona commented on src/resources/tasks.js
> +  const oldTask = tasks.find(((task) => task.id === Number(taskId)));
We're not handling here the possibility that the task the user wants to edit doesn't exists so we should ask if `oldTasks` exists and if it doesn't we should show an error message like "Task with the id ${taskId} not found"

2022-10-12 04:11 UTC, baudraccoverona commented on src/resources/tasks.js
> +      res.send('Can not edit task');
We should improve this error message to be something like "Could not edit task with the id ${taskId}"

2022-10-12 04:11 UTC, baudraccoverona commented on src/resources/tasks.js
> +      res.send('Task edited successfully');
We should improve this success message to be something like this "Task edited successfully ${task[index].id}"

2022-10-13 14:36 UTC, DinoStampella commented on src/index.js
> +// Dino Stampella Workspace
Comment removed

2022-10-13 14:36 UTC, DinoStampella commented on src/index.js
> +// End workspace (DS)
Comment removed

2022-10-13 14:43 UTC, DinoStampella commented on src/resources/tasks.js
> +  const oldTask = tasks.find(((task) => task.id === Number(taskId)));
Validation created

2022-10-13 14:44 UTC, DinoStampella commented on src/resources/tasks.js
> +      res.send('Can not edit task');
Msg updated

2022-10-13 14:46 UTC, DinoStampella commented on src/resources/tasks.js
> +      res.send('Task edited successfully');
Msg updated

2022-10-13 23:26 UTC, DinoStampella commented on src/resources/tasks.js
> +      res.send('Task created successfully');
Msg updated

2022-10-14 00:43 UTC, baudraccoverona approved these changes
Looking good! 🚀

2022-10-14 00:43 UTC, merged