BaSP-TG: get, getAll and delete (Employee)
BaSP-a2022/ayom-b-trackgenix-server pull request #13
Opened 2022-10-11 18:01 UTC by EmanuelMuises95

Create method getAll for all employees
Create method get by id
Create method delete by id

2022-10-12 03:39 UTC, baudraccoverona commented on src/index.js
> +app.use('/employees', require('./resources/employees'));
Please move this logic below the `/admins` `app.get`

2022-10-12 03:41 UTC, baudraccoverona commented on src/resources/employees.js
> +router.get('/getAll', (req, res) => {
this method should be only `/employees` since it's the general denomination for the get all

2022-10-12 03:43 UTC, baudraccoverona commented on src/resources/employees.js
> +    res.send('Employee NOT FOUND');
We could improve this error message to something like this "Employee with the id ${employeeId} not found"

2022-10-12 03:44 UTC, baudraccoverona commented on src/resources/employees.js
> +    res.send('Employee NOT FOUND');
We could improve this error message to something like this "Employee with the id ${employeeId} not found"

2022-10-12 03:45 UTC, baudraccoverona commented on src/resources/employees.js
> +    res.send(`Employee deleted ${findEmployee.name}`);
The success message should only be sent inside the writeFile because this way we're assuming that the employee was deleted without even entering the method to delete it so something can easily fail and we would be sending the user the wrong answer

2022-10-12 03:45 UTC, baudraccoverona commented on src/resources/employees.js
> +      }
In order to solve the comment above we should add an else clause here and do `res.send(`Employee deleted ${findEmployee.name}`);`

2022-10-12 03:47 UTC, baudraccoverona commented on src/resources/employees.js
> +  const findEmployee = employees.find((employee) => employee.id === employeeId);
I think it will be most understandable if this variable was called `foundEmployee`

2022-10-12 03:47 UTC, baudraccoverona commented on src/resources/employees.js
> +  const checkEmployee = employees.find((employee) => employee.id === employeeId);
I think it will be most understandable if this variable was called `foundEmployee`

2022-10-12 03:49 UTC, baudraccoverona requested changes
Please solve the comments I left 😄

2022-10-13 00:15 UTC, EmanuelMuises95 commented on src/resources/employees.js
> +router.get('/getAll', (req, res) => {
Change done

2022-10-13 00:15 UTC, EmanuelMuises95 commented on src/resources/employees.js
> +    res.send('Employee NOT FOUND');
Message changed

2022-10-13 00:15 UTC, EmanuelMuises95 commented on src/resources/employees.js
> +    res.send('Employee NOT FOUND');
Message changed

2022-10-13 00:16 UTC, EmanuelMuises95 commented on src/resources/employees.js
> +    res.send(`Employee deleted ${findEmployee.name}`);
Updated

2022-10-13 00:16 UTC, EmanuelMuises95 commented on src/resources/employees.js
> +      }
else with message added

2022-10-13 00:16 UTC, EmanuelMuises95 commented on src/resources/employees.js
> +  const findEmployee = employees.find((employee) => employee.id === employeeId);
variable changed

2022-10-13 00:16 UTC, EmanuelMuises95 commented on src/resources/employees.js
> +  const checkEmployee = employees.find((employee) => employee.id === employeeId);
variable name changed

2022-10-13 00:41 UTC, baudraccoverona commented on src/resources/employees.js
> +  const checkEmployee = employees.find((employee) => employee.id === employeeId);
I'm seeing the same name as before

2022-10-13 00:42 UTC, baudraccoverona requested changes
Please change the variable name 🙏

2022-10-13 04:42 UTC, EmanuelMuises95 commented on src/resources/employees.js
> +  const checkEmployee = employees.find((employee) => employee.id === employeeId);
I'll review it

2022-10-13 19:40 UTC, EmanuelMuises95 commented
> Please change the variable name 🙏

Name changed.

2022-10-13 19:42 UTC, baudraccoverona approved these changes
Good to go! 🚀

2022-10-13 19:42 UTC, merged