BaSP-TG: Task / Delete & Find with filter
BaSP-a2022/ayom-b-trackgenix-server pull request #14
Opened 2022-10-11 19:33 UTC by JulianFloresDev

> Create methods to find task with filters by:

- "task"
- "id"
- "date"

> Create method to delete task filter by:

- "id"
- "date"
- "task"

2022-10-12 03:37 UTC, baudraccoverona requested changes

2022-10-12 03:37 UTC, baudraccoverona commented on src/index.js
> +//! Julian Flores & Diaz Camila workspace:
We should remove this comment since it's not providing any information about understanding the code

2022-10-12 03:37 UTC, baudraccoverona commented on src/index.js
> +//! End workspace (JF).
We should remove this comment since it's not providing any information about understanding the code

2022-10-12 03:37 UTC, baudraccoverona commented on src/resources/time-sheets.js
> +/* eslint-disable import/no-import-module-exports */
We shouldn't disable ESLint rules, please remove the three lines above and solve the issues 😄

2022-10-12 03:37 UTC, baudraccoverona commented on src/resources/time-sheets.js
> +router.get('/getByArgument', (req, res) => {
We should rename this method to `getBy/:prop` in order to be more accurate and keep consistency between all the files

2022-10-12 03:37 UTC, baudraccoverona commented on src/resources/time-sheets.js
> +      .send('This data dosen\'t match with any time sheet! Please check data entry');
There is a typo in here, please 🧹  the `\`

2022-10-12 03:37 UTC, baudraccoverona commented on .vscode/settings.json
> +  "editor.fontSize": 15,
Please remove this, this configs should be in your vs code config, not the project don't (the only config we'll allow is the `tabSize` one because we have an ESLint rule for that)

2022-10-12 03:37 UTC, baudraccoverona commented on .vscode/settings.json
> +  "editor.fontFamily": "'Cascadia Code LP',Consolas, 'Courier New', monospace",
Same as above

2022-10-12 03:37 UTC, baudraccoverona commented on .vscode/settings.json
> +  "editor.fontLigatures": true,
Same as above

2022-10-12 03:37 UTC, baudraccoverona commented on src/resources/time-sheets.js
> +    res.send('None changes done');
You should change this message in order to be more accurate. Something like "Timesheet not found"

2022-10-12 03:37 UTC, baudraccoverona commented on src/resources/time-sheets.js
> +          .send('Could not edit the file!');
You should change this meesage in order to be more accurate. Something like "Timesheet ${timeSheetFound} could not be deleted"

2022-10-12 03:37 UTC, baudraccoverona commented on src/resources/time-sheets.js
> +        res.json(newTimeSheetList);
You should change this meesage in order to be more accurate. Something like "Timesheet deleted successfully ${newTimeSheetList}"

2022-10-12 11:59 UTC, JulianFloresDev commented on src/resources/time-sheets.js
> +router.get('/getByArgument', (req, res) => {
If I make this change, I will need to create 3 get methods; one for each one of them.

With this type of call, I make a callback with the `findOnReq(request)` function to check which property has been called, and then return the JSON file with those files in it.

2022-10-12 12:34 UTC, baudraccoverona commented on src/resources/time-sheets.js
> +router.get('/getByArgument', (req, res) => {
The suggestion was to add the /:prop or /:argument or the name you want to call it, mostly to add the ":param" to the route of the method in order to give more clarity

2022-10-12 14:24 UTC, JulianFloresDev commented on src/index.js
> +//! Julian Flores & Diaz Camila workspace:
Change Done!

2022-10-12 14:25 UTC, JulianFloresDev commented on src/resources/time-sheets.js
> +      .send('This data dosen\'t match with any time sheet! Please check data entry');
Change Done!

2022-10-12 14:25 UTC, JulianFloresDev commented on .vscode/settings.json
> +  "editor.fontFamily": "'Cascadia Code LP',Consolas, 'Courier New', monospace",
File add to gitignore!

2022-10-12 14:25 UTC, JulianFloresDev commented on .vscode/settings.json
> +  "editor.fontLigatures": true,
File add to gitignore

2022-10-12 14:26 UTC, JulianFloresDev commented on src/resources/time-sheets.js
> +        res.json(newTimeSheetList);
Change Done!

2022-10-13 13:54 UTC, baudraccoverona requested changes

2022-10-13 13:54 UTC, baudraccoverona commented on .vscode/settings.json
> +  "editor.fontSize": 15,
Please do the same as Ayom asked in the other PR because this config should not be merged. You should remove the file from the git ignore, delete these changes, push again. And then add those lines of code and add the file into de ignore. If you have any concerns please reach out to me and we'll fix this.

2022-10-13 14:04 UTC, JulianFloresDev commented on .vscode/settings.json
> +  "editor.fontSize": 15,
Is it possible that there is some kind of mistake? It doesn't appear in my vscode since I merge from master

2022-10-13 16:32 UTC, baudraccoverona approved these changes
Nice job! 🚀

2022-10-13 16:32 UTC, merged