BaSP-TG-3: Create methods and resources to Admin
BaSP-a2022/ayom-b-trackgenix-server pull request #16
Opened 2022-10-15 00:17 UTC by JulianFloresDev

Create:

-  Admin Schema
- admin routes to:
- - Get by Id
- - Delete by Id
- - Edit Admin by Id

2022-10-16 16:21 UTC, ignacioaristo requested changes

2022-10-16 16:21 UTC, ignacioaristo commented on src/controllers/admins.js
> +    return res.status(408)
lets change this code too

2022-10-16 16:21 UTC, ignacioaristo commented on src/controllers/admins.js
> +      { ...req.body },
i think spread operator here is not necessary, we could do `req.body` and we get the same result.

2022-10-16 16:21 UTC, ignacioaristo commented on src/controllers/admins.js
> +        message: 'Something was wrong!',
Same error message

2022-10-16 16:43 UTC, ignacioaristo requested changes

2022-10-16 16:43 UTC, ignacioaristo commented on src/controllers/admins.js
> +      error: false,
Is not necessary to show the error when an error occurs

2022-10-16 18:55 UTC, JulianFloresDev commented on src/controllers/admins.js
> +    return res.status(302).json({
Changes done!

2022-10-16 18:56 UTC, JulianFloresDev commented on src/controllers/admins.js
> +    return res.status(408)
Change done!

2022-10-16 18:59 UTC, JulianFloresDev commented on src/controllers/admins.js
> +        message: 'Something was wrong!',
I didn't know that was possible, I mean to manipulate the error received from the catch for the error message.

Change in progress!

2022-10-16 19:01 UTC, JulianFloresDev commented on src/controllers/admins.js
> +    return res.status(408)
Change in progress

2022-10-16 19:01 UTC, JulianFloresDev commented on src/controllers/admins.js
> +        message: 'Something was wrong!',
Change Done

2022-10-16 19:01 UTC, JulianFloresDev commented on src/controllers/admins.js
> +    return res.status(408)
Change Done

2022-10-16 19:02 UTC, JulianFloresDev commented on src/controllers/admins.js
> +      { ...req.body },
I honestly didn't know why Capi did that.

2022-10-16 19:03 UTC, JulianFloresDev commented on src/controllers/admins.js
> +      { ...req.body },
Change Done

2022-10-16 19:03 UTC, JulianFloresDev commented on src/controllers/admins.js
> +        message: 'Something was wrong!',
Done

2022-10-16 19:07 UTC, JulianFloresDev commented on src/controllers/admins.js
> +      error: false,
I'm not sure what you mean here.

Is about 'error' property? That is not necessary?

2022-10-16 19:14 UTC, JulianFloresDev commented on src/controllers/admins.js
> +      { ...req.body },
The slint does not allow me to remove the spread operator; it tells me that it is missing a comma.

2022-10-17 00:27 UTC, ignacioaristo requested changes

2022-10-17 00:27 UTC, ignacioaristo commented on src/controllers/admins.js
> +        error: err,
I think now, this prop is unnecessary

2022-10-17 00:27 UTC, ignacioaristo commented on src/controllers/admins.js
> +        error: false,
We don't need this prop too.

2022-10-17 00:27 UTC, ignacioaristo commented on src/controllers/admins.js
> +        error: err,
The same here.

2022-10-17 00:27 UTC, ignacioaristo commented on src/controllers/admins.js
> +        error: false,
And here too.

2022-10-17 00:27 UTC, ignacioaristo commented on src/controllers/admins.js
> +        error: err,
Delete this.

2022-10-17 00:27 UTC, ignacioaristo commented on src/controllers/admins.js
> +        message: 'Something was wrong!',
Handle the message error like before.

2022-10-17 00:36 UTC, JulianFloresDev commented
All suggested changes have been implemented!

2022-10-17 01:19 UTC, merged