BaSP-TG-14/Project controller (getById-delete-update)
BaSP-a2022/ayom-b-trackgenix-server pull request #19
Opened 2022-10-16 23:49 UTC by cami-diaz

1. Create project schema.
2. Create routes for projects.
3. Create controllers for projects (getById-delete-update).
4. Apply validation for update.

2022-10-17 00:59 UTC, ignacioaristo requested changes
Remember to update the Postman collection with the endpoints of projects.

2022-10-17 00:59 UTC, ignacioaristo commented on Readme.md
>  ### Members
This belong to another ticket, please remove it from here and create another branch for this [ticket](https://trello.com/c/3rqBy5mP/2-update-readme).

2022-10-17 00:59 UTC, ignacioaristo commented on src/models/Projects.js
> +// eslint-disable-next-line import/no-unresolved
Remove this rule.

2022-10-17 00:59 UTC, ignacioaristo commented on src/routes/projects.js
> +  .get('/getById/:id', projects.getProjectById)
Remember that we have changed this, now we assume with the `.get` we are getting by id, so we have to to only `.get(/:id)`

2022-10-17 00:59 UTC, ignacioaristo commented on src/routes/projects.js
> +  .put('/update/:id', projectsValidation.validateCreation, projects.updateProject)
The same here

2022-10-17 00:59 UTC, ignacioaristo commented on src/routes/projects.js
> +  .delete('/delete/:id', projects.deleteProject);
and here

2022-10-17 00:59 UTC, ignacioaristo commented on src/validations/projects.js
> +      data: undefined,
data in not necessary when you are showing the error.

2022-10-17 00:59 UTC, ignacioaristo commented on src/validations/projects.js
> +      error: true,
This is not necessary too.

2022-10-17 00:59 UTC, ignacioaristo commented on src/controllers/projects.js
> +        data: undefined,
is not necessary retrieve the data with undefined.

2022-10-17 00:59 UTC, ignacioaristo commented on src/controllers/projects.js
> +        error: true,
show a boolean value for the error is not necessary for now. Remove all.

2022-10-17 00:59 UTC, ignacioaristo commented on src/controllers/projects.js
> +    if (!req.params.id) {
is this working correctly?  How do i get this error?

2022-10-17 00:59 UTC, ignacioaristo commented on src/controllers/projects.js
> +      msg: 'There was an error',
I think we can handle the message error better, we can do something like `msg: 'There was an error: ${error}',`

2022-10-17 00:59 UTC, ignacioaristo commented on src/controllers/projects.js
> +      data: error,
If we do the previous comment, this is not necessary.

2022-10-17 00:59 UTC, ignacioaristo commented on src/controllers/projects.js
> +      msg: 'Project was not found',
Same error handling.

2022-10-17 00:59 UTC, ignacioaristo commented on src/controllers/projects.js
> +      msg: 'There was an error',
Same here

2022-10-17 23:00 UTC, cami-diaz commented on src/controllers/projects.js
> +    if (!req.params.id) {
I remove it because it was and old code that I forgot to remove.

2022-10-17 23:59 UTC, JulianFloresDev commented on src/controllers/projects.js
> +    const project = await Projects.findById({ _id: req.params.id });
Hi Cami!! I think you confused the methods of 'findById' with 'findOne'. findOne requires an object as a parameter; while 'findById' requires a string equivalent to an '_id' within the object to be found.

You could try passing the parameter 'req.params.id'.

https://mongoosejs.com/docs/api/model.html#model_Model-findById:~:text=Finds%20a%20single,_id%3A%20null%20%7D).

2022-10-18 00:00 UTC, JulianFloresDev commented on src/controllers/projects.js
> +    const projectToDelete = await Projects.findByIdAndDelete({ _id: req.params.id });
Same as line 5.

https://mongoosejs.com/docs/api/model.html#model_Model-findByIdAndDelete

2022-10-18 00:01 UTC, JulianFloresDev commented on src/controllers/projects.js
> +    const projectToUpdate = await Projects.findByIdAndUpdate(
Same here! Try to send a number as param in 'findByIdAndUpdate'

2022-10-18 00:12 UTC, JulianFloresDev commented on src/validations/projects.js
> +    employee: Joi.array().items(employeeValidation),
Would it be possible to send an empty array here?

Like:

'employee': [ ],

I suggest using something like the following

https://joi.dev/api/?v=17.6.1#general-usage:~:text=%2C%20array.ref-,array.min(limit),-Specifies%20the%20minimum

2022-10-18 12:33 UTC, ignacioaristo commented on src/controllers/projects.js
> +        error: false,
Remove this prop, i think is not necessary for now.
Do it in all the code.

2022-10-19 14:35 UTC, ignacioaristo requested changes

2022-10-19 14:35 UTC, ignacioaristo commented on src/controllers/projects.js
> +      error: true,
remove all this errors props.

2022-10-20 18:16 UTC, ignacioaristo approved these changes

2022-10-20 18:17 UTC, merged