BaSP-TG-12: TimeSheet (GetById, DeleteById and EditById)
BaSP-a2022/ayom-b-trackgenix-server pull request #21
Opened 2022-10-17 01:38 UTC by NicolasGulam

Created for TimeSheet Section Linking in Index file, Model, Validations, Routes and Functions GetById, DeleteById and EditById.

2022-10-17 17:49 UTC, ignacioaristo requested changes

2022-10-17 17:49 UTC, ignacioaristo commented on src/controllers/timeSheets.js
> +// Get by Id
This comment is redundant, with the name of the function below we know it.

2022-10-17 17:49 UTC, ignacioaristo commented on src/controllers/timeSheets.js
> +      error: false,
i think this prop is not necessary.

2022-10-17 17:49 UTC, ignacioaristo commented on src/controllers/timeSheets.js
> +      message: 'An error ocurred',
we can handle the error message, showing the error in this line.

2022-10-17 17:49 UTC, ignacioaristo commented on src/controllers/timeSheets.js
> +// Delete by Id
same with this comment.

2022-10-17 17:49 UTC, ignacioaristo commented on src/controllers/timeSheets.js
> +      error: false,
same here., remove all

2022-10-17 17:49 UTC, ignacioaristo commented on src/validations/timeSheets.js
> +      data: undefined,
i think this prop is not necessary, as the line below.

2022-10-17 21:38 UTC, NicolasGulam commented on src/validations/timeSheets.js
> +      data: undefined,
All corrections have been made

2022-10-18 16:37 UTC, ignacioaristo requested changes

2022-10-18 16:37 UTC, ignacioaristo commented on src/data/time-sheets.json
>  [{
Delete this file, now, we are using the data base.

2022-10-18 21:16 UTC, NicolasGulam commented on src/data/time-sheets.json
>  [{
Done.

2022-10-18 21:18 UTC, NicolasGulam commented on src/data/time-sheets.json
>  [{
I saw that i have new conflicts to resolve

2022-10-19 12:33 UTC, ignacioaristo approved these changes

2022-10-20 15:15 UTC, ignacioaristo submitted a review, later dismissed

2022-10-21 02:54 UTC, ignacioaristo approved these changes

2022-10-21 02:54 UTC, merged