BaSP-TG-5: SuperAdmins (GetAll and Create)
BaSP-a2022/ayom-b-trackgenix-server pull request #22
Opened 2022-10-17 04:24 UTC by NicolasGulam

Created for SuperAdmins Section: Linking in Index file, Model, Validations, Routes and Functions GetAll and Create.

2022-10-17 13:02 UTC, ignacioaristo requested changes

2022-10-17 13:02 UTC, ignacioaristo commented on src/validations/superAdmins.js
> +      data: undefined,
we don't need to show the data if we get undefined, remove this and the line below.

2022-10-17 21:28 UTC, NicolasGulam commented on src/controllers/superAdmins.js
> +  } catch (error) {
All corrections have been made

2022-10-19 14:33 UTC, ignacioaristo approved these changes

2022-10-20 15:14 UTC, merged