BaSP-TG-09: Employee (Get all - Create)
BaSP-a2022/ayom-b-trackgenix-server pull request #23
Opened 2022-10-17 17:35 UTC by Licamus

Creations of the methods get all and create for employee. I modified the index.js, controllers, valitidations and create a new schema for employee

2022-10-17 17:41 UTC, ignacioaristo requested changes

2022-10-17 17:41 UTC, ignacioaristo commented on src/controllers/employees.js
> +      error: false,
I think this prop is not necessary.

2022-10-17 17:41 UTC, ignacioaristo commented on src/controllers/employees.js
> +      message: 'An error ocurred',
we can handle this message in a better way, for example: `message: 'An error ocurred': ${error},`

2022-10-17 17:41 UTC, ignacioaristo commented on src/controllers/employees.js
> +  } catch (error) {
for consistency, change all `errors` to `err`

2022-10-17 17:41 UTC, ignacioaristo commented on src/controllers/employees.js
> +      error: false,
same as before.

2022-10-17 17:41 UTC, ignacioaristo commented on src/validations/employees.js
> +      data: undefined,
for me, this is not necessary.

2022-10-17 17:49 UTC, Licamus commented on src/controllers/employees.js
> +      error: false,
You are talking about error: false? After the metting of today, i let the error prop stay anyway thinking about a possible future use for the API consumer.  If is not necessary in this stage, tell me and i will delete the prop.

2022-10-17 17:49 UTC, Licamus commented on src/controllers/employees.js
> +      error: false,
You are talking about error: false? After the metting of today, i let the error prop stay anyway thinking about a possible future use for the API consumer.  If is not necessary in this stage, tell me and i will delete the prop.

2022-10-18 12:57 UTC, ignacioaristo requested changes

2022-10-18 12:57 UTC, ignacioaristo commented on src/validations/employees.js
> +      error: true,
Same here

2022-10-18 14:26 UTC, Licamus commented on src/controllers/employees.js
> +      error: false,
Done!

2022-10-18 14:26 UTC, Licamus commented on src/controllers/employees.js
> +      message: 'An error ocurred',
Done!

2022-10-18 14:26 UTC, Licamus commented on src/controllers/employees.js
> +  } catch (error) {
Done!

2022-10-18 14:26 UTC, Licamus commented on src/controllers/employees.js
> +      error: false,
Done!

2022-10-18 14:26 UTC, Licamus commented on src/validations/employees.js
> +      data: undefined,
Done!

2022-10-18 16:40 UTC, ignacioaristo requested changes
Remove the file of employee inside data folder. Now we are using the Data Base.

2022-10-18 16:46 UTC, ignacioaristo requested changes

2022-10-18 16:46 UTC, ignacioaristo commented on src/controllers/employees.js
> +      error: err,
Remove this error.

2022-10-18 16:46 UTC, ignacioaristo commented on src/controllers/employees.js
> +    return res.json({
Status code is missing.

2022-10-18 16:46 UTC, ignacioaristo commented on src/controllers/employees.js
> +      error: err,
remove this line

2022-10-18 20:41 UTC, Licamus commented on src/controllers/employees.js
> +      error: err,
Done!

2022-10-18 20:41 UTC, Licamus commented on src/controllers/employees.js
> +      error: err,
Done!

2022-10-18 20:43 UTC, Licamus commented on src/controllers/employees.js
> +    return res.json({
done!

2022-10-19 14:17 UTC, ignacioaristo requested changes

2022-10-19 14:17 UTC, ignacioaristo commented on src/controllers/employees.js
> +      message: 'An error ocurred',
I don't see the change here.

2022-10-19 14:51 UTC, Licamus commented on src/controllers/employees.js
> +      message: 'An error ocurred',
It doesn't save, done now!

2022-10-19 20:04 UTC, ignacioaristo approved these changes

2022-10-19 20:05 UTC, merged