BaSP-TG: Projects method (GET-DELETE-POST)
BaSP-a2022/ayom-b-trackgenix-server pull request #3
Opened 2022-10-08 23:31 UTC by cami-diaz

1. Update the readme.
2. Create the projects.json .
3. Create logic to get projects by id.

2022-10-10 20:18 UTC, Licamus reviewed
Post method review

2022-10-10 20:18 UTC, Licamus commented on src/resources/projects.js
> +router.post('/', (req, res) => {
You can send a void body and its storages anyway?

2022-10-10 20:18 UTC, Licamus commented on src/resources/projects.js
> +  const newProject = req.body;
if you send a body with wrongs keys, its storages anyway?

2022-10-11 19:29 UTC, ignacioaristo requested changes

2022-10-11 19:29 UTC, ignacioaristo commented on src/resources/projects.js
> +router.get('/:id', (req, res) => {
We should name the route `'/getById/:id` in order to specify the property that we want to get by.

2022-10-11 19:29 UTC, ignacioaristo commented on src/resources/projects.js
> +  const found = projects.find((project) => String(project.id) === req.params.id);
We need to be more specific with the name of variables. For e.g: project or projectFiltered, etc.

2022-10-11 19:29 UTC, ignacioaristo commented on src/resources/projects.js
> +    res.status(200).json(projects.filter((project) => String(project.id) === req.params.id));
Is this filter neccesary? We are doing it in the line above.

2022-10-11 19:29 UTC, ignacioaristo commented on src/resources/projects.js
> +router.delete('/:id', (req, res) => {
We should name the route `'/delete/:id'` in order to specify the property that we want to get by.

2022-10-11 19:29 UTC, ignacioaristo commented on src/resources/projects.js
> +    res.send('Could not delete because the time sheet was not found');
Time sheet or project? We need to fix the msg.

2022-10-11 19:29 UTC, ignacioaristo commented on src/resources/projects.js
> +        res.status(200).send(filterTs);
We should show a confirmation message that the project was deleted successfully instead of the list of projects.

2022-10-11 19:29 UTC, ignacioaristo commented on src/resources/projects.js
> +router.post('/', (req, res) => {
We should name the route `'/create'` to be more specific.

2022-10-12 12:50 UTC, ignacioaristo commented
> method

Resolved.

2022-10-12 12:50 UTC, merged