BaSP-TG: Admin
BaSP-a2022/ayom-b-trackgenix-server pull request #4
Opened 2022-10-09 18:09 UTC by jivescovo

Maxi and I created all methods together during meet calls that have been logged in the minutas file.

2022-10-10 19:24 UTC, cami-diaz commented
shouldn't the readme be updated?

2022-10-10 19:26 UTC, cami-diaz commented on package.json
> +    "express": "^4.18.1",
Is it necessary to change the version of express?

2022-10-10 19:26 UTC, cami-diaz commented on package.json
> +  "version": "0.0.1",
Is it necessary to change the version ?

2022-10-12 00:18 UTC, ignacioaristo requested changes

2022-10-12 00:18 UTC, ignacioaristo commented on src/resources/admins.js
> +router.post('/addAdmin', (req, res) => {
We could name it like `add` or `create`. We know that is an admin for the previous path.

2022-10-12 00:18 UTC, ignacioaristo commented on src/resources/admins.js
> +router.get('/getListAdmin/:id/:name/:lastName/:email/:password', (req, res) => {
This get is weird, we should filter by 1 property in specific. For example with the `id` or `name`. Not all of them.

2022-10-12 15:04 UTC, ignacioaristo submitted a review, later dismissed

2022-10-12 17:26 UTC, ignacioaristo approved these changes
Good job

2022-10-12 17:26 UTC, merged