Projects Edit / Add Employee / Get by filters
BaSP-a2022/ayom-b-trackgenix-server pull request #5
Opened 2022-10-09 19:20 UTC by JulianFloresDev

En el JSON, en el primer proyecto la lista de empleados asociado quedó con un exceso de 2 empleados de prueba generados desde Postman, ignorarlos.

2022-10-10 20:06 UTC, NicolasGulam commented
Juli fijate que no respetaste esto: El nombre de las PR deben respetar el formato BaSP-TG: Short description

2022-10-12 01:05 UTC, ignacioaristo requested changes
All the messages in github must be in English.

2022-10-12 01:05 UTC, ignacioaristo commented on src/resources/projects.js
> +router.get('/getByArgument', (req, res, next) => {
Same for this next

2022-10-12 01:05 UTC, ignacioaristo commented on src/resources/projects.js
> +const findProjectOnReq = (request) => {
Nice function.

2022-10-12 14:22 UTC, JulianFloresDev commented on src/index.js
> +//! Julian Flores & Diaz Camila workspace:
Change Done!

2022-10-12 14:22 UTC, JulianFloresDev commented on src/index.js
> +app.use('/projects', require('./resources/projects'));
Change Done!

2022-10-12 14:22 UTC, JulianFloresDev commented on .vscode/settings.json
> +  "editor.fontSize": 15,
Change Done!

2022-10-12 14:23 UTC, JulianFloresDev commented on src/resources/projects.js
> +import express from 'express';
Change Done!

2022-10-12 14:23 UTC, JulianFloresDev commented on src/resources/projects.js
> +router.put('/edit/project/:id', (req, res) => {
Change Done!

2022-10-12 14:23 UTC, JulianFloresDev commented on src/resources/projects.js
> +router.get('/getAll', (req, res, next) => {
Change Done!

2022-10-12 14:23 UTC, JulianFloresDev commented on src/resources/projects.js
> +router.get('/getAll', (req, res, next) => {
Change Done!

2022-10-12 14:23 UTC, JulianFloresDev commented on src/resources/projects.js
> +router.get('/getByArgument', (req, res, next) => {
Change Done!

2022-10-12 14:23 UTC, JulianFloresDev commented on src/resources/projects.js
> +const findProjectOnReq = (request) => {
Thanks!

2022-10-12 17:40 UTC, ignacioaristo commented on .vscode/settings.json
> +  "editor.fontSize": 15,
Juli, we need to fix something. Remove the file from the git ignore, delete these changes, push again. And then add those lines of code and add the file into de ignore. If you have any doubt MD me.

2022-10-12 19:35 UTC, JulianFloresDev commented on .vscode/settings.json
> +  "editor.fontSize": 15,
Changes done!!

2022-10-13 12:24 UTC, ignacioaristo approved these changes

2022-10-13 12:24 UTC, merged