BaSP-TG-53: CHANGE GetAll method returns 200 when list is empty
BaSP-a2022/ayom-b-trackgenix-server pull request #55
Opened 2022-11-04 21:22 UTC by fede230298

CHANGE all entities to send status 200 when fetching an empty list.
RE-ARRANGE test to validate the new status and messages

2022-11-04 22:56 UTC, Ignacio-Sormani requested changes
I see that you only updated tests for 3 resources. Are there missing tests? Please add them

2022-11-04 22:56 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      return res.status(200).json({
Both success responses are the same. I think we should just keep one return 200 with same message: 'Admin List"

2022-11-04 22:56 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      return res.status(200).json({
Apply same comment for all the controllers

2022-11-04 23:03 UTC, fede230298 commented on src/controllers/admins.js
> +      return res.status(200).json({
So I should remove the conditional !entity.length and leave just the 200 status when OK?

2022-11-05 02:28 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      return res.status(200).json({
Yes, it will always return the array even if it's empty

2022-11-06 03:01 UTC, GonzaloAsencio approved these changes

2022-11-06 20:21 UTC, Ignacio-Sormani approved these changes

2022-11-06 21:11 UTC, javierperezraffo approved these changes

2022-11-06 21:13 UTC, merged