BaSP-TG-54: Fix getById method for Admins entity
BaSP-a2022/ayom-b-trackgenix-server pull request #56
Opened 2022-11-04 22:50 UTC by JuliMonte5

1. getById method was returning status 200 for non-existent Ids in the DB
2. Also included a validation for a correct Id format (to be a mongoose type)

2022-11-04 23:04 UTC, Ignacio-Sormani requested changes

2022-11-04 23:04 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      message: `Cannot get Admin by ${req.params.id}`,
The message should be something like:
`${req.params.id} is an invalid id`

2022-11-04 23:04 UTC, Ignacio-Sormani commented on src/controllers/admins.js
>      const { id } = req.params;
Move this to the first line of the function

2022-11-04 23:04 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      message: `Admin with id ${req.params.id} not found`,
Just use id const

2022-11-05 02:26 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      message: `Cannot get Admin by ${req.params.id}`,
This was resolved in https://github.com/BaSP-a2022/ayom-b-trackgenix-server/pull/57

2022-11-06 03:00 UTC, GonzaloAsencio approved these changes

2022-11-07 00:21 UTC, Ignacio-Sormani approved these changes

2022-11-07 02:32 UTC, sofihoj approved these changes

2022-11-07 02:38 UTC, merged