BaSP-TG-55: Added check for valid id
BaSP-a2022/ayom-b-trackgenix-server pull request #57
Opened 2022-11-04 23:00 UTC by MaicolFreire001

Added a function in all controllers to check if the used id for the request is a valid mongoDB id. 
Also fixed all test that stopped working with these changes

2022-11-04 23:12 UTC, Ignacio-Sormani requested changes
You only updated tests for three controllers. If there are missing tests please add them

2022-11-04 23:12 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +const { ObjectId } = require('mongoose').Types;
Use import instead of require

2022-11-04 23:12 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +const isValidObjectId = (id) => {
This can be written as a single line function. It would be something like this:
`const isValidObjectId = id => ObjectId.isValid(id) && (String)(new ObjectId(id)) === id);`

2022-11-04 23:12 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +const { ObjectId } = require('mongoose').Types;
Apply this change in all the controllers

2022-11-04 23:12 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +const isValidObjectId = (id) => {
Apply this change in all the controllers

2022-11-04 23:12 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      return res.status(404)
.json should start in same line than res.status

2022-11-04 23:12 UTC, Ignacio-Sormani commented on src/controllers/admins.js
>        { _id: id },
You can just write `id` instead of `{ _id: id },`

2022-11-04 23:12 UTC, Ignacio-Sormani commented on src/controllers/admins.js
>        { _id: id },
Apply this change in all the controllers

2022-11-04 23:25 UTC, MaicolFreire001 commented on src/controllers/admins.js
> +const { ObjectId } = require('mongoose').Types;
Done

2022-11-04 23:27 UTC, MaicolFreire001 commented on src/controllers/admins.js
> +const isValidObjectId = (id) => {
Done

2022-11-04 23:57 UTC, MaicolFreire001 commented on src/controllers/admins.js
> +      return res.status(404)
done

2022-11-04 23:59 UTC, MaicolFreire001 commented on src/controllers/admins.js
>        { _id: id },
Done

2022-11-05 02:25 UTC, Ignacio-Sormani submitted a review, later dismissed

2022-11-05 16:16 UTC, ignacioaristo submitted a review, later dismissed

2022-11-06 02:59 UTC, GonzaloAsencio approved these changes

2022-11-07 02:40 UTC, Ignacio-Sormani commented
Please resolve conflicts

2022-11-09 20:21 UTC, Ignacio-Sormani submitted a review, later dismissed

2022-11-09 21:18 UTC, Ignacio-Sormani approved these changes

2022-11-09 21:18 UTC, merged