BaSP-TG-52: Standarize errors code
BaSP-a2022/ayom-b-trackgenix-server pull request #59
Opened 2022-11-05 22:36 UTC by GonzaloAsencio

Change all the code states and adapt them in the tests.
All catches have to return status code 500 and validations status code 400

Messages for all entities must follow the same pattern:
**Status code 200**
**GetAll**: <entities> found.
**GetById**: <entity> found.
**Put**: <entity> with id ${id} updated successfully.

 **Status code 201**
**Post**: <entity> created successfully.

**Status code 404**
 <entity> with id ${id} not found.

**Status code 500**
Cannot get <entity> with id ${id}.

2022-11-06 20:53 UTC, Ignacio-Sormani commented
Please also standarize status codes for successful respones:

GET -> 200
POST, PUT -> 201
DELETE -> 204

2022-11-06 20:53 UTC, Ignacio-Sormani requested changes

2022-11-06 20:53 UTC, Ignacio-Sormani commented on .vs/VSWorkspaceState.json
> +{
I don't think we need this file. Please remove it

2022-11-06 20:53 UTC, Ignacio-Sormani commented on .vs/VSWorkspaceState.json
> +{
Also remove the file under .vs/backend/v17/.suo

2022-11-06 21:30 UTC, GonzaloAsencio commented on .vs/VSWorkspaceState.json
> +{
removed!

2022-11-07 02:39 UTC, Ignacio-Sormani commented
There are some conflicts in the PR

2022-11-07 15:02 UTC, GonzaloAsencio commented
Resolved conflicts!

2022-11-07 18:37 UTC, sofihoj commented on src/controllers/admins.js
>        });
When is a successful response you can add error: false

2022-11-07 18:37 UTC, sofihoj commented on src/controllers/projects.js
>        });
When is a successful response you can add error: false

2022-11-07 18:37 UTC, sofihoj commented on src/controllers/projects.js
>        });
When is a successful response you can add error: false

2022-11-07 18:37 UTC, sofihoj commented on src/controllers/projects.js
>      });
When is a successful response you can add error: false

2022-11-07 18:37 UTC, sofihoj commented on src/controllers/projects.js
>      });
When is a successful response you can add error: false

2022-11-07 18:37 UTC, sofihoj commented on src/controllers/superAdmins.js
>      });
When is a successful response you can add error: false

2022-11-07 18:37 UTC, sofihoj commented on src/controllers/superAdmins.js
>      });
When is a successful response you can add error: false

2022-11-07 18:37 UTC, sofihoj commented on src/controllers/projects.js
>          data: projectToDelete,
The 204 status code is a No Content success status response code, so I think that data should not be included

2022-11-07 21:37 UTC, GonzaloAsencio commented on src/controllers/projects.js
>        });
Done

2022-11-07 21:37 UTC, GonzaloAsencio commented on src/controllers/projects.js
>        });
Done

2022-11-07 21:38 UTC, GonzaloAsencio commented on src/controllers/projects.js
>      });
Done

2022-11-07 21:38 UTC, GonzaloAsencio commented on src/controllers/projects.js
>      });
Done

2022-11-07 21:39 UTC, GonzaloAsencio commented on src/controllers/superAdmins.js
>      });
Done

2022-11-07 21:39 UTC, GonzaloAsencio commented on src/controllers/superAdmins.js
>      });
Done

2022-11-07 21:40 UTC, GonzaloAsencio commented on src/controllers/projects.js
>          data: projectToDelete,
Removed

2022-11-07 23:45 UTC, Ignacio-Sormani requested changes
I'm sorry for the amount of comments. Most of them are repeated.

There are some 400 and 404 responses that were not in the endpoints. This will be addressed in ticket TG-55

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +    return res.status(500).json({
According to ticket description, it should be status 400 and message: 'Cannot get admin with id ${id}'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      throw new Error(`Admin with id:${id} not found`);
Should not throw an error since it is not goind to be handled correctly in catch block. Use res.send with status 404 and correct message

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +    return res.status(500)
Include .json({ at the end of the line

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/projects.js
> +      message: `Project with id:${req.params.id} not found`,
Add error property

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/projects.js
>      });
Add error

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/projects.js
> +      message: 'Cannot create Project',
Add error

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/projects.js
> +      message: `Cannot edit Project with id ${req.params.id}`,
Add error

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/superAdmins.js
> +      message: 'Cannot create admin',
Add error

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/superAdmins.js
> +      message: `Cannot edit Admin with id:${req.params.id}`,
Add error

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/tasks.js
>      return res.status(200)
Write .json({ at the end of res.status

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/timeSheets.js
> +      message: 'Cannot get TimeSheet',
Add error

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/timeSheets.js
> +      message: 'Cannot delete TimeSheet',
Add error

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/timeSheets.js
> +      message: 'Cannot gets TimeSheets',
Should be 'Cannot get TimeSheets'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/timeSheets.js
> +      message: 'Cannot gets TimeSheets',
Add error

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/timeSheets.js
> +      message: 'Cannot create TimeSheet',
Add error

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      message: 'Cannot get admins',
Should be '... Admins'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      message: 'Cannot create admin',
Should be '... Admin'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/employees.js
> +      message: 'Cannot get employees',
Should be '... Employees'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/projects.js
> +        message: `Project with id:${req.params.id} delete successfully`,
Should be 'deleted'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/projects.js
> +      message: `Can not delete Project with ID: ${req.params.id}`,
Should be 'Cannot ...'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/projects.js
> +      message: 'Cannot get projects',
Should be '... Projects'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/superAdmins.js
> +      message: 'Cannot get super admins',
Should be '... Super Admins'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/superAdmins.js
> +      message: `Cannot get super admin with id:${req.params.id}`,
Should be 'Super Admin'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/superAdmins.js
> +      message: 'Cannot create admin',
Should be 'Admin'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/tasks.js
> +        message: 'Cannot get tasks',
Should be 'Tasks'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/tasks.js
> +        message: 'Cannot get tasks',
Should be 'Tasks'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      message: `Admin with id:${id} delete successfully`,
Should be 'deleted'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/employees.js
> +      message: `Employee with id:${id} delete successfully`,
Should be 'deleted'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      message: `Admin with id:${id} delete successfully`,
Should be 'deleted'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/tasks.js
> +        message: `Task with id:${req.params.id} delete successfully`,
Should be 'deleted'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/admins.js
> +      message: `Admin with id:${id} delete successfully`,
Should be 'deleted'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/timeSheets.js
> +      message: `TimeSheet with id:${req.params.id} delete successfully`,
Should be 'deleted'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/superAdmins.js
> +        message: `Super Admin with id:${id} delete successfully`,
Should be 'deleted'

2022-11-07 23:45 UTC, Ignacio-Sormani commented on src/controllers/employees.js
> +      message: `Employee with id:${id} delete successfully`,
Should be 'deleted'

2022-11-08 02:56 UTC, GonzaloAsencio commented on src/controllers/admins.js
> +    return res.status(500).json({
Changed!

2022-11-08 02:59 UTC, GonzaloAsencio commented on src/controllers/admins.js
> +      throw new Error(`Admin with id:${id} not found`);
Changed

2022-11-08 03:00 UTC, GonzaloAsencio commented on src/controllers/admins.js
> +    return res.status(500)
Changed

2022-11-08 03:11 UTC, GonzaloAsencio commented on src/controllers/projects.js
> +      message: `Project with id:${req.params.id} not found`,
Done

2022-11-08 03:12 UTC, GonzaloAsencio commented on src/controllers/projects.js
>      });
Done

2022-11-08 03:12 UTC, GonzaloAsencio commented on src/controllers/projects.js
> +      message: 'Cannot create Project',
Done

2022-11-08 03:12 UTC, GonzaloAsencio commented on src/controllers/projects.js
> +      message: `Cannot edit Project with id ${req.params.id}`,
Done

2022-11-08 03:17 UTC, GonzaloAsencio commented on src/controllers/superAdmins.js
> +      message: `Cannot edit Admin with id:${req.params.id}`,
Done

2022-11-08 03:17 UTC, GonzaloAsencio commented on src/controllers/superAdmins.js
> +      message: 'Cannot create admin',
Done

2022-11-08 03:25 UTC, GonzaloAsencio commented on src/controllers/tasks.js
>      return res.status(200)
Done

2022-11-08 03:26 UTC, GonzaloAsencio commented on src/controllers/timeSheets.js
> +      message: 'Cannot get TimeSheet',
Done

2022-11-08 03:26 UTC, GonzaloAsencio commented on src/controllers/timeSheets.js
> +      message: 'Cannot delete TimeSheet',
Done

2022-11-08 03:27 UTC, GonzaloAsencio commented on src/controllers/timeSheets.js
> +      message: 'Cannot gets TimeSheets',
Done

2022-11-08 03:28 UTC, GonzaloAsencio commented on src/controllers/timeSheets.js
> +      message: 'Cannot gets TimeSheets',
Done

2022-11-08 03:28 UTC, GonzaloAsencio commented on src/controllers/timeSheets.js
> +      message: 'Cannot create TimeSheet',
Done

2022-11-08 03:28 UTC, GonzaloAsencio commented on src/controllers/admins.js
> +      message: 'Cannot get admins',
Done

2022-11-08 03:28 UTC, GonzaloAsencio commented on src/controllers/admins.js
> +      message: 'Cannot create admin',
Done

2022-11-08 03:29 UTC, GonzaloAsencio commented on src/controllers/employees.js
> +      message: 'Cannot get employees',
Done

2022-11-08 03:30 UTC, GonzaloAsencio commented on src/controllers/projects.js
> +        message: `Project with id:${req.params.id} delete successfully`,
done

2022-11-08 03:30 UTC, GonzaloAsencio commented on src/controllers/projects.js
> +      message: `Can not delete Project with ID: ${req.params.id}`,
Done

2022-11-08 03:31 UTC, GonzaloAsencio commented on src/controllers/projects.js
> +      message: 'Cannot get projects',
Done

2022-11-08 03:32 UTC, GonzaloAsencio commented on src/controllers/superAdmins.js
> +      message: 'Cannot get super admins',
Done

2022-11-08 03:32 UTC, GonzaloAsencio commented on src/controllers/superAdmins.js
> +      message: `Cannot get super admin with id:${req.params.id}`,
Done

2022-11-08 03:33 UTC, GonzaloAsencio commented on src/controllers/superAdmins.js
> +      message: 'Cannot create admin',
Done

2022-11-08 03:34 UTC, GonzaloAsencio commented on src/controllers/tasks.js
> +        message: 'Cannot get tasks',
Done

2022-11-08 03:35 UTC, GonzaloAsencio commented on src/controllers/tasks.js
> +        message: 'Cannot get tasks',
Done

2022-11-08 03:36 UTC, GonzaloAsencio commented on src/controllers/admins.js
> +      message: `Admin with id:${id} delete successfully`,
Done

2022-11-08 03:37 UTC, GonzaloAsencio commented on src/controllers/employees.js
> +      message: `Employee with id:${id} delete successfully`,
Donde

2022-11-08 03:37 UTC, GonzaloAsencio commented on src/controllers/admins.js
> +      message: `Admin with id:${id} delete successfully`,
Done

2022-11-08 03:37 UTC, GonzaloAsencio commented on src/controllers/tasks.js
> +        message: `Task with id:${req.params.id} delete successfully`,
Done

2022-11-08 03:37 UTC, GonzaloAsencio commented on src/controllers/admins.js
> +      message: `Admin with id:${id} delete successfully`,
Done

2022-11-08 03:39 UTC, GonzaloAsencio commented on src/controllers/employees.js
> +      message: `Employee with id:${id} delete successfully`,
Done

2022-11-08 03:39 UTC, GonzaloAsencio commented on src/controllers/timeSheets.js
> +      message: `TimeSheet with id:${req.params.id} delete successfully`,
Done

2022-11-08 03:39 UTC, GonzaloAsencio commented on src/controllers/superAdmins.js
> +        message: `Super Admin with id:${id} delete successfully`,
Done

2022-11-08 04:41 UTC, Ignacio-Sormani approved these changes

2022-11-08 18:08 UTC, sofihoj approved these changes
Great work!

2022-11-08 19:23 UTC, Ignacio-Sormani approved these changes

2022-11-08 19:24 UTC, merged