BaSP-TG: superadmins methods (create, delete and filter)
BaSP-a2022/ayom-b-trackgenix-server pull request #9
Opened 2022-10-10 20:08 UTC by DinoStampella

2022-10-11 18:38 UTC, Licamus commented on src/resources/super-admins.js
> +// GET BY FILTERS
It is possible to filter with more than 1 parameter at the same time?

2022-10-11 18:55 UTC, DinoStampella commented on src/resources/super-admins.js
> +// GET BY FILTERS
In this case, you can filter one parameter at a time.

2022-10-12 02:04 UTC, ignacioaristo requested changes

2022-10-12 02:04 UTC, ignacioaristo commented on src/resources/super-admins.js
> +  if (Object.keys(newSuperAdmin).length !== 5) {
With this validation, we can enter any key, no matter the name.

2022-10-12 02:04 UTC, ignacioaristo commented on src/resources/super-admins.js
> +  const newID = Number(superAdmins[superAdmins.length - 1].id) + 1;
Good one, the next week we are not going to need this, the id will be generated automatically.

2022-10-12 02:04 UTC, ignacioaristo commented on src/resources/super-admins.js
> +      res.send('SuperAdmin created successfully');
We can show the new data, for e.g:
`      res.send('SuperAdmin created successfully: ${newSuperAdmin}');`

2022-10-12 17:05 UTC, DinoStampella commented on src/resources/super-admins.js
> +  const newID = Number(superAdmins[superAdmins.length - 1].id) + 1;
Great! So do I remove this validation?

2022-10-12 17:46 UTC, ignacioaristo commented on src/resources/super-admins.js
> +  const newID = Number(superAdmins[superAdmins.length - 1].id) + 1;
I would say yes, just in case.

2022-10-13 14:32 UTC, DinoStampella commented on src/resources/super-admins.js
> +  if (Object.keys(newSuperAdmin).length !== 5) {
Validation added

2022-10-13 14:32 UTC, DinoStampella commented on src/resources/super-admins.js
> +  const newID = Number(superAdmins[superAdmins.length - 1].id) + 1;
newId removed

2022-10-13 14:32 UTC, DinoStampella commented on src/resources/super-admins.js
> +      res.send('SuperAdmin created successfully');
Message updated

2022-10-13 16:37 UTC, baudraccoverona approved these changes
Good to go ✨

2022-10-13 16:38 UTC, merged